---
- name: Configure EC2 with Docker and Nginx
  hosts: ec2
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy HTML page
      copy:
        src: files/index.html
        dest: /home/ubuntu/index.html
        mode: '0644'

    - name: Run Nginx Container
      docker_container:
        name: nginx_web
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/index.html:/usr/share/nginx/html/index.html:ro
